# Generated by Django 4.2.7 on 2025-08-08 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(max_length=500, verbose_name='Tóm tắt')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('news_type', models.CharField(choices=[('internal', 'Tin nội bộ'), ('industry', 'Tin ngành'), ('system', 'Thông báo hệ thống'), ('regulation', 'Quy định mới'), ('market', 'Thị trường')], max_length=20, verbose_name='Loại tin')),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('normal', 'Bình thường'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='normal', max_length=20, verbose_name='Độ ưu tiên')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã xuất bản'), ('archived', 'Lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tin nổi bật')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Ghim tin')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Hình ảnh đại diện')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất bản')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_news', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Tin tức',
                'ordering': ['-is_pinned', '-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Màu sắc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Danh mục tin tức',
                'verbose_name_plural': 'Danh mục tin tức',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('notification_type', models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('error', 'Lỗi'), ('success', 'Thành công'), ('maintenance', 'Bảo trì')], max_length=20, verbose_name='Loại thông báo')),
                ('target_roles', models.CharField(blank=True, help_text='Các role cách nhau bằng dấu phẩy', max_length=200, verbose_name='Vai trò nhận')),
                ('is_global', models.BooleanField(default=False, verbose_name='Thông báo toàn hệ thống')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('start_date', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('target_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Người nhận cụ thể')),
            ],
            options={
                'verbose_name': 'Thông báo hệ thống',
                'verbose_name_plural': 'Thông báo hệ thống',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người bình luận')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news', verbose_name='Tin tức')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.newscomment', verbose_name='Bình luận gốc')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.newscategory', verbose_name='Danh mục'),
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đọc')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_status', to='news.systemnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đọc')),
            ],
            options={
                'verbose_name': 'Trạng thái đọc thông báo',
                'verbose_name_plural': 'Trạng thái đọc thông báo',
                'unique_together': {('notification', 'user')},
            },
        ),
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian xem')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người xem')),
            ],
            options={
                'verbose_name': 'Lượt xem tin tức',
                'verbose_name_plural': 'Lượt xem tin tức',
                'unique_together': {('news', 'user', 'ip_address')},
            },
        ),
    ]
