# Generated by Django 4.2.7 on 2025-08-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active_employee',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_customer',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('premium_customer', 'Khách hàng VIP'), ('business_customer', 'Khách hàng doanh nghiệp')], default='customer', max_length=20, verbose_name='Loại khách hàng'),
        ),
    ]
