# Generated by Django 4.2.7 on 2025-08-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên công ty')),
                ('company_type', models.CharField(choices=[('our_company', 'Công ty chúng tôi'), ('supplier', 'Nhà cung cấp'), ('customer', 'Khách hàng'), ('partner', 'Đối tác')], max_length=20, verbose_name='Loại công ty')),
                ('tax_code', models.CharField(max_length=20, unique=True, verbose_name='Mã số thuế')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Tên ngân hàng')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Người liên hệ')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='SĐT người liên hệ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email người liên hệ')),
                ('import_license', models.CharField(blank=True, max_length=50, verbose_name='Giấy phép nhập khẩu')),
                ('export_license', models.CharField(blank=True, max_length=50, verbose_name='Giấy phép xuất khẩu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Công ty',
                'verbose_name_plural': 'Công ty',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('business_license', 'Giấy phép kinh doanh'), ('tax_certificate', 'Giấy chứng nhận thuế'), ('import_license', 'Giấy phép nhập khẩu'), ('export_license', 'Giấy phép xuất khẩu'), ('other', 'Khác')], max_length=20, verbose_name='Loại tài liệu')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('file', models.FileField(upload_to='company_documents/', verbose_name='File tài liệu')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company')),
            ],
            options={
                'verbose_name': 'Tài liệu công ty',
                'verbose_name_plural': 'Tài liệu công ty',
            },
        ),
    ]
