# Generated by Django 4.2.7 on 2025-08-22 14:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='VD: Nhà riêng, Công ty', max_length=50, verbose_name='Nhãn địa chỉ')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Tên người nhận')),
                ('phone', models.CharField(max_length=17, verbose_name='Số điện thoại người nhận')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('address', models.TextField(verbose_name='Địa chỉ chi tiết')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
            ],
            options={
                'verbose_name': 'Địa chỉ giao hàng',
                'verbose_name_plural': 'Địa chỉ giao hàng',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=20, unique=True, verbose_name='Mã khách hàng')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải có định dạng: '+999999999'. Tối đa 15 chữ số.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Số điện thoại')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('address', models.TextField(verbose_name='Địa chỉ chi tiết')),
                ('membership_level', models.CharField(choices=[('bronze', 'Đồng'), ('silver', 'Bạc'), ('gold', 'Vàng'), ('platinum', 'Bạch kim')], default='bronze', max_length=10, verbose_name='Cấp thành viên')),
                ('points', models.IntegerField(default=0, verbose_name='Điểm tích lũy')),
                ('preferred_products', models.TextField(blank=True, verbose_name='Sản phẩm ưa thích')),
                ('preferred_payment_method', models.CharField(blank=True, max_length=50, verbose_name='Phương thức thanh toán ưa thích')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Tổng số đơn hàng')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng chi tiêu')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác minh')),
                ('is_vip', models.BooleanField(default=False, verbose_name='Khách hàng VIP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Hồ sơ khách hàng',
                'verbose_name_plural': 'Hồ sơ khách hàng',
            },
        ),
        migrations.CreateModel(
            name='CustomerWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='customer_portal.customerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Sản phẩm yêu thích',
                'verbose_name_plural': 'Sản phẩm yêu thích',
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá')),
                ('comment', models.TextField(verbose_name='Bình luận')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Đã mua hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='customer_portal.customerprofile')),
            ],
            options={
                'verbose_name': 'Đánh giá sản phẩm',
                'verbose_name_plural': 'Đánh giá sản phẩm',
            },
        ),
    ]
