@echo off
echo Setting up Customer Database...
cd /d "d:\IT\summer-2\QLDA\customer"

echo Making migrations...
python manage.py makemigrations

echo Applying migrations...
python manage.py migrate

echo Creating sample data...
python create_sample_data.py

echo Starting development server on port 8001...
python manage.py runserver 8001
