# Generated by Django 4.2.7 on 2025-08-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_code', models.CharField(max_length=20, unique=True, verbose_name='Mã nông dân')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nông dân / trang trại')),
                ('farm_type', models.CharField(choices=[('small', 'Nông hộ nhỏ'), ('medium', 'Nông hộ vừa'), ('large', 'Nông trại lớn')], max_length=20, verbose_name='Loại hình nông hộ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('farm_area', models.FloatField(default=0, verbose_name='Diện tích (ha)')),
                ('main_product', models.CharField(max_length=100, verbose_name='Sản phẩm')),
                ('crop', models.CharField(help_text='Loại cây trồng', max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Nông dân',
                'verbose_name_plural': 'Nông dân',
            },
        ),
    ]
