# Generated by Django 4.2.7 on 2025-08-22 14:17

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('role', models.CharField(choices=[('farmer', 'Nông dân'), ('farm_manager', 'Quản lý nông trại'), ('cooperative_member', 'Thành viên hợp tác xã')], default='farmer', max_length=20, verbose_name='Vai trò')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('is_active_employee', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Nông dân',
                'verbose_name_plural': 'Nông dân',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True, verbose_name='Mã nhân viên')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Phòng ban')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Chức vụ')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Ngày vào làm')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Lương')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ nhân viên',
                'verbose_name_plural': 'Hồ sơ nhân viên',
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100, verbose_name='Tên nông trại')),
                ('farmer_code', models.CharField(max_length=20, unique=True, verbose_name='Mã nông dân')),
                ('farmer_type', models.CharField(choices=[('individual', 'Cá nhân'), ('cooperative', 'Hợp tác xã'), ('small_farm', 'Nông trại nhỏ'), ('organic_farm', 'Nông trại hữu cơ')], default='individual', max_length=20)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ', regex='^\\+?1?\\d{9,15}$')], verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('farm_address', models.TextField(verbose_name='Địa chỉ nông trại')),
                ('province', models.CharField(max_length=50, verbose_name='Tỉnh/Thành phố')),
                ('district', models.CharField(max_length=50, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=50, verbose_name='Phường/Xã')),
                ('farm_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diện tích (ha)')),
                ('main_products', models.TextField(help_text='Liệt kê các loại trái cây chính', verbose_name='Sản phẩm chính')),
                ('certification', models.CharField(choices=[('none', 'Chưa có'), ('organic', 'Hữu cơ'), ('vietgap', 'VietGAP'), ('globalgap', 'GlobalGAP')], default='none', max_length=20)),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Số năm kinh nghiệm')),
                ('established_date', models.DateField(verbose_name='Ngày thành lập/bắt đầu')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác thực')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ nông dân',
                'verbose_name_plural': 'Hồ sơ nông dân',
                'ordering': ['-created_at'],
            },
        ),
    ]
