# Generated by Django 4.2.7 on 2025-08-08 15:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Số đơn hàng')),
                ('order_type', models.CharField(choices=[('export', 'Xuất khẩu'), ('import', 'Nhập khẩu'), ('domestic_sale', 'Bán nội địa'), ('domestic_purchase', 'Mua nội địa')], max_length=20, verbose_name='Loại đơn hàng')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('shipped', 'Đã giao hàng'), ('delivered', 'Đã nhận hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('partial', 'Thanh toán một phần'), ('paid', 'Đã thanh toán'), ('overdue', 'Quá hạn')], default='pending', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Ngày giao hàng')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Ngày giao dự kiến')),
                ('shipping_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('shipping_contact', models.CharField(blank=True, max_length=100, verbose_name='Người nhận')),
                ('shipping_phone', models.CharField(blank=True, max_length=15, verbose_name='SĐT người nhận')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng tiền hàng')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tiền thuế')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Phí vận chuyển')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Giảm giá')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng cộng')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='Trạng thái cũ')),
                ('to_status', models.CharField(max_length=20, verbose_name='Trạng thái mới')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thay đổi')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thay đổi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái',
                'verbose_name_plural': 'Lịch sử trạng thái',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Hợp đồng'), ('invoice', 'Hóa đơn'), ('packing_list', 'Danh sách đóng gói'), ('bill_of_lading', 'Vận đơn'), ('certificate', 'Chứng chỉ'), ('other', 'Khác')], max_length=20, verbose_name='Loại tài liệu')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('file', models.FileField(upload_to='order_documents/', verbose_name='File')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.order')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'Tài liệu đơn hàng',
                'verbose_name_plural': 'Tài liệu đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Thành tiền')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Thuế suất (%)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Giảm giá (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
